### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Kundby** [dkaksl/steam#6]
Hey

I've tried to use your code, as a way to sign in to Steam for my Android app
Though when i try to compile and run, it's giving me this error: 
Error: Program type already present: org.aopalliance.intercept.MethodInvocation

All i've done is add your dependency to my gradle, so far, with limited code of my own(worked beforehand)

Is there a way i can contact you, and share my code if you're up to help?

Thanks in advance
Kundby

**Comment by dkaksl** [comment]
Hi! I'm happy to see my project is actually reaching someone. I've never actually used this library in an Android project, so there's a good chance it won't work out of the box.

It would be nice if it did, though, so I might try it myself, and if it's not too complicated, I'll publish a fix.

Btw, it looks like [that error message means you have a naming conflict in your dependencies](https://stackoverflow.com/a/49767860). E.g. one of your libraries is conflicting with mine somehow. You might be able to work around it by using a different constellation of dependencies.

**Comment by Kundby** [comment]
> Hi! I'm happy to see my project is actually reaching someone. I've never actually used this library in an Android project, so there's a good chance it won't work out of the box.
> 
> It would be nice if it did, though, so I might try it myself, and if it's not too complicated, I'll publish a fix.
> 
> Btw, it looks like [that error message means you have a naming conflict in your dependencies](https://stackoverflow.com/a/49767860). E.g. one of your libraries is conflicting with mine somehow. You might be able to work around it by using a different constellation of dependencies.

Hey

Ye, I've figured out that it's naming conflict, but the place it origins from is your library, so i hoped you'd heard of it before :)

I'll try and find a solution, and reply back when/if i figure it out

**Comment by dkaksl** [comment]
Sorry, never got around to this. I'm archiving the repo, hence closing old issues.
